#! /bin/sh

# Startups
sxhkd &
$HOME/.config/polybar/launch-round.sh &
picom --config ~/.config/picom/picom.conf --experimental-backends -b &
alsactl --file ~/.config/asound.state restore
setroot --restore &
/usr/bin/emacs --daemon &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a firefox desktop='^3'
bspc rule -a discord desktop='^4'
bspc rule -a element desktop='^4'
bspc rule -a Pcmanfm state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
