#! /bin/sh

sxhkd &
picom --config ~/.config/picom/picom.conf --experimental-backends -b &
alsactl --file ~/.config/asound.state restore
setroot --restore &
/usr/bin/emacs --daemon &
polybar example &

bspc monitor -d sys dev web discord teams documentation music video virtualbox

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a emacs state='tiled'
bspc rule -a qutebrowser desktop='^3'
bspc rule -a discord desktop='^4'
bspc rule -a pcmanfm state='floating'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
