# autogenerated by txs
#include:hopatch
\csname#S
\__hook hopatch#S
\__hook package/after/xcolor#S
\__hook_next package/after/xcolor#S
\__hook_toplevel package/after/xcolor#S
\g__hook_package/after/xcolor_code_prop#S
\g__hook_package/after/xcolor_labels_clist#S
\g__hook_package/after/xcolor_reversed_tl#S
\unprocessedoptions-hopatch.sty#S
csnameendcsname#S
hopatch.sty#S
