# autogenerated by txs
#include:xcolor
\applycolormixins{arg1}#S
\begin{colormixin}#S
\colorcurrentmixin#S
\csname#S
\end{colormixin}#S
\newcolormixin{arg1}#S
\pgfalternateextension#S
\__hook xcolor#S
\unprocessedoptions-xcolor.sty#S
csnameendcsname#S
xcolor.sty#S
