#!/bin/sh

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Create gap for polybar
bspc config bottom_padding $(($(bspc config bottom_padding)+35))

# Start all the bars
polybar top &
polybar bottom &
